shop_products:
    resource: "@ShopProductsBundle/Controller/"
    type:     annotation
    prefix:   /

shop_front:
    resource: "@ShopFrontBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /
    defaults: { _locale: fr }
    requirements:
        _locale: fr|en
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
    defaults: { _locale: fr }
    requirements:
        _locale: fr|en
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
    defaults: { _locale: fr }
    requirements:
        _locale: fr|en
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
    defaults: { _locale: fr }
    requirements:
        _locale: fr|en
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    defaults: { _locale: fr }
    requirements:
        _locale: fr|en