<?php

namespace Shop\ProductsBundle\Repository;

/**
 * MainImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainImageRepository extends \Doctrine\ORM\EntityRepository
{
}
